#!/usr/bin/env bash

set -eu

base=$(dirname ${BASH_SOURCE[0]})
SCREENSHOTS_LOCATION=${SCREENSHOTS_LOCATION:-..}

help () {
  echo "Usage:"
  echo "  $(basename $0)"
  echo "Copies/rsyncs files from the checkout into this repository"
}

if [[ ! -f "$SCREENSHOTS_LOCATION/server/src/server.js" ]] ; then
  echo "Looked in $SCREENSHOTS_LOCATION (\$SCREENSHOTS_LOCATION) for a checkout, did not find one"
  help
  exit 1
fi

rsync -rvalp \
  --delete \
  --filter ":- $SCREENSHOTS_LOCATION/.gitignore" \
  --exclude "$(basename "$(pwd)")" \
  --exclude rsync-files \
  --exclude ABOUT.md \
  --exclude .git \
  --exclude .babelrc \
  --exclude /.ebextensions/ \
  --exclude /setup.cfg \
  --exclude package.json \
  --exclude /server/ \
  --exclude "Docker*" \
  --exclude "docker*" \
  --exclude ".docker*" \
  --include /bin/ \
  --include /bin/build-scripts/ \
  --include /bin/build-scripts/css_to_js.py \
  --include /bin/build-scripts/modularize \
  --include /bin/build-scripts/set_file \
  --include /bin/build-scripts/update_manifest.py \
  --exclude "/bin/build-scripts/*" \
  --exclude "/bin/*" \
  --include /static/ \
  --include /static/js/ \
  --include /static/js/wantsauth.js \
  --exclude "/static/js/*" \
  --include /static/css/ \
  --include /static/css/inline-selection.scss \
  --include /static/css/partials/ \
  --exclude "/static/css/*" \
  --exclude "/static/*" \
  $SCREENSHOTS_LOCATION .
