DELETE FROM STATES WHERE DEVICEID NOT IN
(SELECT DEVICEID FROM STATES, DEVICES WHERE STATES.DEVICEID = DEVICES.ID);
ALTER TABLE ONLY states
ADD CONSTRAINT states_deviceid_fkey FOREIGN KEY (deviceid) REFERENCES devices(id) ON DELETE CASCADE;
