ALTER TABLE data ADD head TEXT;
ALTER TABLE data ADD body TEXT;

CREATE TABLE images (
  id VARCHAR(200) PRIMARY KEY,
  shotid VARCHAR(200) NOT NULL REFERENCES data (id) ON DELETE CASCADE,
  clipid VARCHAR(200) NOT NULL,
  image BYTEA NOT NULL,
  contenttype TEXT NOT NULL
);
